#pragma once

#include "UI_BasicBase.h"
#include "UI_InstanceBase.h"
#include "UIScene.h"

namespace Client
{
	enum MON_TYPE { MON_BONE, MON_FULLFACE, MON_TRIPLEPUT, MON_END };
	enum INS_MAIN { INS_MAIN_GAMESTART, INS_MAIN_EXIT, INS_MAIN_PARARIGHT, INS_MAIN_PARALEFT, INS_MAIN_END};
	enum INS_PLAYER { INS_PLAYER_HP, INS_PLAYER_BATTERY, INS_PLAYER_BATTERYCASE, INS_PALEYR_SKILLDIR, INS_PLAYER_END};
	enum UI_INBATTLE_PLAYER { UI_INBATTLE_PLAYERHITNUM_0, UI_INBATTLE_PLAYERHITNUM_1, UI_INBATTLE_PLAYERHIT, UI_INBATTLE_PLAYER_END};
	enum INS_BOSS { INS_BOSS_PHASELEFT, INS_BOSS_PHASERIGHT, INS_BOSS_PHASE1HP, INS_BOSS_PHASE2HP, INS_BOSS_END };
	enum INS_MONSTER {INS_MONSTER_HP, INS_MONSTER_END};
	enum INS_NAMED { INS_NAMED_PHASELEFT, INS_NAMED_PHASERIGHT, INS_NAMED_HP, INS_NAMED_END };
	enum INS_LETTER { INS_LETTER_KILL, INS_LETTER_MR, INS_LETTER_BLACKHOLE, INS_LETTER_SONIC, INS_LETTER_JUICE, INS_LETTER_DEAD, INS_LETTER_QUESTIONMARK, INS_LETTER_END};
	enum FINALSLAH_DIR { FINALSLAH_DIR_D, FINALSLAH_DIR_L, FINALSLAH_DIR_R, FINALSLAH_DIR_SD, FINALSLAH_DIR_SV, FINALSLAH_DIR_V, FINALSLAH_DIR_END};
	enum UI_PLAYER_STATUS {
		UI_STATUS_BACK, UI_SLIDEBAR, UI_NUM1, UI_NUM2, UI_NUM1_PRESS, UI_NUM2_PRESS, UI_STATUS_INFO, UI_STATUS_MAIN, UI_STATUS_PLAYER_BG, UI_STATUS_PLAYER_CUR, 
		UI_BUFF_BOX_HP, UI_BUFF_BOX_POWER, UI_BUFF_BOX_CHARGE,
		UI_STATUS_SPECIAL_MUSTANG, UI_STATUS_SPECIAL_KICK, UI_STATUS_SPECIAL_TRANSFORM, UI_STATUS_SPECIAL_SLOW, UI_STATUS_SPECIAL_OFF,
		UI_STATUS_ICON_HP, UI_STATUS_ICON_POWER, UI_STATUS_ICON_CHARGE, UI_STATUS_ICON_HP_PLUS, UI_STATUS_ICON_POWER_PLUS, UI_STATUS_ICON_CHARGE_PLUS, UI_STATUS_JEANEBOX1, UI_STATUS_JEANEBOX2,
		UI_OPTION_INFO, UI_OPTION_MAIN, UI_SET, UI_SET_PRESS, UI_TITLE, UI_TITLE_PRESS, UI_OPTION_SAVE, UI_OPTION_SAVE_PRESS, UI_SELECT, UI_STATUS_END
	};
	enum UI_MOVEBUTTON { UI_MOVEBUTTON_A0, UI_MOVEBUTTON_A1, UI_MOVEBUTTON_A2, UI_MOVEBUTTON_A3, UI_MOVEBUTTON_A4, UI_MOVEBUTTON_A5, UI_MOVEBUTTON_A_END };
	enum UI_MOVE_STAT { UI_MOVE_IN, UI_MOVE_OUT, UI_MOVE_TEXTIO, UI_MOVE_IDLE, UI_MOVE_END };
	enum UI_BATTLE_RESULT { UI_BATTLE_RESULT_BLACKBG, UI_BATTLE_RESULT_BG,
		UI_BATTLE_RESULT_RESULT, UI_BATTLE_RESULT_CLEARTIME, UI_BATTLE_RESULT_GETDAMAGED, UI_BATTLE_RESULT_SKILLCNT,
		UI_BATTLE_RESULT_PLAYERSKILLALL, UI_BATTLE_RESULT_RANK, UI_BATTLE_RESULT_RANKICON, UI_BATTLE_RESULT_REWARD, UI_BATTLE_RESULT_END };
	enum UI_BATTLE_RANK { UI_BATTLE_RANK_SS, UI_BATTLE_RANK_S, UI_BATTLE_RANK_A, UI_BATTLE_RANK_B, UI_BATTLE_RANK_C, UI_BATTLE_RANK_D, UI_BATTLE_RANK_END };
	enum UI_TOILET { UI_TOILET_TISSUE_LEFT, UI_TOILET_TISSUE_RIGHT, UI_TOILET_CHECKPOINT, UI_TOILET_END };
	enum UI_LOADING { UI_LOAD_BACK, UI_LOAD_STAR, UI_LOADING_END };
	enum UI_INTRO { UI_INTRO_BACK, UI_INTRO_LOGO, UI_INTRO_END };
	enum UI_HOME { UI_HOME_EXIT, UI_HOME_EXIT_2F, UI_HOME_JEANE, UI_HOME_ROBE, UI_HOME_POLE, UI_HOME_POLE_2F, UI_HOME_FIGURE, UI_HOME_CAT_FOOD, UI_HOME_END };
	enum UI_SUSHISHOP { UI_SUSHISHOP_BG, UI_SUSHISHOP_BLACKBG, UI_SUSHISHOP_ICON, UI_SUSHISHOP_KEYGUIDE, UI_SUSHISHOP_PLAYERSTATUS, UI_SUSHISHOP_POPUPTEXT,
		UI_SUSHISHOP_TAB1_MENU0, UI_SUSHISHOP_TAB1_MENU1, UI_SUSHISHOP_TAB1, UI_SUSHISHOP_TAB1_SUSHI1, UI_SUSHISHOP_TAB1_SUSHI2, UI_SUSHISHOP_TAB1_SUSHI3, UI_SUSHISHOP_TAB1_SUSHI4, UI_SUSHISHOP_TAB1_SUSHI5, UI_SUSHISHOP_TAB1_SUSHI6,
		UI_SUSHISHOP_TAB2_MENU, UI_SUSHISHOP_TAB2, UI_SUSHISHOP_TAB2_DISH1, UI_SUSHISHOP_TAB2_DISH2, UI_SUSHISHOP_TAB2_DISH3, UI_SUSHISHOP_TAB2_DISH4, UI_SUSHISHOP_TAB2_DISH5, UI_SUSHISHOP_TAB2_DISH6, UI_SUSHISHOP_TAB2_DISH7,
		UI_SUSHISHOP_TAB2_SUSHI1, UI_SUSHISHOP_TAB2_SUSHI2, UI_SUSHISHOP_TAB2_SUSHI3, UI_SUSHISHOP_TAB2_SUSHI4, UI_SUSHISHOP_TAB2_SUSHI5, UI_SUSHISHOP_TAB2_SUSHI6, UI_SUSHISHOP_TAB2_SUSHI7,
		UI_SUSHISHOP_BLACKBGPOP, UI_SUSHISHOP_POPUPBG, UI_SUSHISHOP_POPUPICON, UI_SUSHISHOP_POPUPLBTN, UI_SUSHISHOP_POPUPRBTN, UI_SUSHISHOP_POPUPLINE, UI_SUSHISHOP_POPUP_NUMBACK1, UI_SUSHISHOP_POPUP_NUMBACK2, UI_SUSHISHOP_POPUP_TAB1IMG, UI_SUSHISHOP_POPUP_DISH, UI_SUSHISHOP_POPUP_TAB2IMG, UI_SUSHISHOP_END };
	enum UI_TURNRPG { UI_TURNRPG_TOPTEXTAREA, UI_TURNRPG_PLAYERSATEAREA, UI_TURNRPG_PLAYERATTACKAREA, UI_TURNRPG_PLAYERATTACKPOP, UI_TURNRPG_ATTACKTEXT, UI_TURNRPG_SELECTED, UI_TURNRPG_END};
	enum UI_SMASH {
		UI_SMASH_READY, UI_SMASH_FIGHT, UI_SMASH_GAME, UI_SMASH_TRAVIS, UI_SMASH_TRAVISHP, UI_SMASH_DAMONIOCN,
		UI_SMASH_NUMLLL, UI_SMASH_NUMLL, UI_SMASH_NUML, UI_SMASH_NUMS, UI_SMASH_DOT, UI_SMASH_PERSENT,
		UI_SMASH_DAMON_NUMLLL, UI_SMASH_DAMON_NUMLL, UI_SMASH_DAMON_NUML, UI_SMASH_DAMON_NUMS, UI_SMASH_DAMON_DOT, UI_SMASH_DAMON_PERSENT, UI_SMASH_DAMON_END
	};
	enum INS_SMASH {
		INS_SMASH_MINITOP, INS_SMASH_MINILEFT, INS_SMASH_MINIRIGHT, INS_SMASH_MINIBOTTOM, 
		INS_SMASH_TOP, INS_SMASH_LEFT, INS_SMASH_RIGHT, INS_SMASH_BOTTOM, 
		INS_SMASH_TOPICON, INS_SMASH_LEFTICON, INS_SMASH_RIGHTICON, INS_SMASH_BOTTOMICON, INS_SMASH_SKILLDIR, INS_SMASH_DAMON_END
	};
	enum UI_POWERUP {
		UI_POWERUP_BG, 
		UI_POWERUP_WESN_NUM0, UI_POWERUP_WESN_NUM1, UI_POWERUP_WESN_NUM2, UI_POWERUP_WESN_NUM3, UI_POWERUP_WESN_NUM4, UI_POWERUP_WESN_NUM5, 
		UI_POWERUP_REDICON, UI_POWERUP_BLUEICON, UI_POWERUP_GREENICON, UI_POWERUP_PINKICON, UI_POWERUP_YELLOWICON, 
		UI_POWERUP_REDMOVE, UI_POWERUP_BLUEMOVE, UI_POWERUP_GREENMOVE, UI_POWERUP_PINKMOVE, UI_POWERUP_YELLOWMOVE,
		UI_POWERUP_RED_BTN, UI_POWERUP_BLUE_BTN, UI_POWERUP_GREEN_BTN, UI_POWERUP_PINK_BTN, UI_POWERUP_YELLOW_BTN,
		UI_POWERUP_REDLEVEL1, UI_POWERUP_REDLEVEL2, UI_POWERUP_REDLEVEL3, UI_POWERUP_REDLEVEL4, UI_POWERUP_REDLEVEL5, UI_POWERUP_REDLEVEL6, UI_POWERUP_REDLEVEL7, UI_POWERUP_REDLEVEL8, UI_POWERUP_REDLEVEL9, 
		UI_POWERUP_BLUELEVEL1, UI_POWERUP_BLUELEVEL2, UI_POWERUP_BLUELEVEL3, UI_POWERUP_BLUELEVEL4, UI_POWERUP_BLUELEVEL5, UI_POWERUP_BLUELEVEL6, UI_POWERUP_BLUELEVEL7, UI_POWERUP_BLUELEVEL8, UI_POWERUP_BLUELEVEL9, 
		UI_POWERUP_GREENLEVEL1, UI_POWERUP_GREENLEVEL2, UI_POWERUP_GREENLEVEL3, UI_POWERUP_GREENLEVEL4, UI_POWERUP_GREENLEVEL5, 
		UI_POWERUP_PINKLEVEL1, UI_POWERUP_PINKLEVEL2, UI_POWERUP_YELLOWLEVEL1, UI_POWERUP_YELLOWLEVEL2, UI_POWERUP_YELLOWLEVEL3, UI_POWERUP_YELLOWLEVEL4, UI_POWERUP_YELLOWLEVEL5,
		UI_POWERUP_LINERED, UI_POWERUP_LINEBLUE, UI_POWERUP_LINEGREEN, UI_POWERUP_LINEPINK, UI_POWERUP_LINEYELLOW,
		UI_POWERUP_KEYGUIDE, UI_POWERUP_SKILLBIGICON, UI_POWERUP_END
	};
	enum UI_MARIO {
		UI_MARIO_COIN, UI_MARIO_NUMLLL, UI_MARIO_NUMLL, UI_MARIO_NUML, UI_MARIO_TIMEM,
		UI_MARIO_TIMEMM, UI_MARIO_TIMES, UI_MARIO_TIMESS, UI_MARIO_TIMEDOT0, UI_MARIO_TIMEDOT1, UI_MARIO_STAR0, UI_MARIO_STAR1, UI_MARIO_STAR2, UI_MARIO_END
	};
	enum UI_MINIGAME_TOILET {
		UI_TMINI_INIT, UI_TMINI_GUIDE, UI_TMINI_MOUSEGUIDE, UI_TMINI_W, UI_TMINI_A, UI_TMINI_S, UI_TMINI_D,
		UI_TMINI_KEEP, UI_TMINI_KEEPWORLD, UI_TMINI_MOUSE, UI_TMINI_TITLE, UI_TMINI_CIRCLE, UI_TMINI_POS, UI_TMINI_END};
	enum UI_CCTV {
		UI_CCTV_DULLFILTER, UI_CCTV_PLAYERSTATUS, UI_CCTV_TIMER, UI_CCTV_LIVEBG, UI_CCTV_LIVEICON_WIFI, UI_CCTV_LIVEICON_REC, UI_CCTV_LIVEICON_USER, UI_CCTV_LIVEICON_CHAT, UI_CCTV_LIVEICON_SKIP, UI_CCTV_END
	}; 
	enum UI_CCTV_CHAT { UI_CCTV_CHAT_TALKAREA, UI_CCTV_CHAT_TALKICON, UI_CCTV_CHAT_END };
	enum UI_SUBTITLE { UI_SUBTITLE_BACKGROUND, UI_SUBTITLE_END };
	enum UI_KEY_INPUT { INPUT_MOVE, INPUT_F, INPUT_SHIFT, INPUT_ALT, INPUT_END };
	enum UI_LOCKON_POS { LOCKON_L, LOCKON_R, LOCKON_B, LOCKON_END };
	enum UI_VISIBLE { UI_VISIBLE_IDLE, UI_VISIBLE_TRUE, UI_VISIBLE_FALSE, UI_VISIBLE_END };
	enum CCTV_USERTYPE { CCTV_USER_ROUND, CCTV_USER_SUSHI, CCTV_USER_TREE, CCTV_USER_CITIZEN_TOILET, CCTV_USER_CITIZEN_TRASH, CCTV_USER_CITIZEN_ISLAND, CCTV_USER_END };

	typedef struct tUserInfo {
		wstring				wstrName = L"";
		wstring				wstrContent = L"";
		wstring				wstrSceneName = L"";
		CCTV_USERTYPE		eUserType = CCTV_USER_END;
		_float				fTextareaSize = 0;
		_int				iIdx = 0;
		_int				iEnterCnt = 0;
	} CCTV_USER;
}